export const cards = [
    {
        country: "Франция",
        director: "Симус Хейли",
        duration: "25",
        year: "2018",
        description: "О чём-то там Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user123",
        movieId: "1",
        nameRU: "В погоне за Бэнкси",
        nameEN: "Banksy Most Wanted"
    },
    {
        country: "Франция",
        director: "Симус Хейли",
        duration: "25",
        year: "2018",
        description: "О чём-то там",
        image: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user125",
        movieId: "2",
        nameRU: "В погоне за Бэнкси",
        nameEN: "Banksy Most Wanted"
    },
    {
        country: "Франция",
        director: "Симус Хейли",
        duration: "25",
        year: "2018",
        description: "О чём-то там Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        image: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user12",
        movieId: "3",
        nameRU: "В погоне за Бэнкси",
        nameEN: "Banksy Most Wanted"
    },
    {
        country: "Франция",
        director: "Симус Хейли",
        duration: "25",
        year: "2018",
        description: "О чём-то там",
        image: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user123",
        movieId: "4",
        nameRU: "В погоне за Бэнкси",
        nameEN: "Banksy Most Wanted"
    },
    {
        country: "Франция",
        director: "Симус Хейли",
        duration: "25",
        year: "2018",
        description: "lamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint o",
        image: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user111",
        movieId: "5",
        nameRU: "В погоне за Бэнкси",
        nameEN: "Banksy Most Wanted"
    },
    {
        country: "Франция",
        director: "Симус Хейли",
        duration: "25",
        year: "2018",
        description: "tetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat ",
        image: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user123",
        movieId: "6",
        nameRU: "В погоне за Бэнкси",
        nameEN: "Banksy Most Wanted"
    },
    {
        country: "Франция",
        director: "Симус Хейли",
        duration: "25",
        year: "2018",
        description: "О чём-то там",
        image: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user123",
        movieId: "7",
        nameRU: "В погоне за Бэнкси",
        nameEN: "Banksy Most Wanted"
    },
    {
        country: "Франция",
        director: "Симус Хейли",
        duration: "25",
        year: "2018",
        description: "О чём-то там",
        image: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user2525",
        movieId: "8",
        nameRU: "В погоне за Бэнкси",
        nameEN: "Banksy Most Wanted"
    },
    {
        country: "Франция",
        director: "Симус Хейли",
        duration: "25",
        year: "2018",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation",
        image: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user123",
        movieId: "9",
        nameRU: "В погоне за Бэнкси",
        nameEN: "Banksy Most Wanted"
    },
    {
        country: "Франция",
        director: "Симус Хейли",
        duration: "25",
        year: "2018",
        description: "О чём-то там",
        image: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user123",
        movieId: "10",
        nameRU: "В погоне за Бэнкси",
        nameEN: "Banksy Most Wanted"
    },
]

export const cardsSavedMovies = [
    {
        country: "США",
        director: "Роберт Земекис",
        duration: "35",
        year: "2018",
        description: "О чём-то там Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "https://www.film.ru/sites/default/files/styles/thumb_1024x450/public/movies/frames/1615989-1576855.jpeg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user123",
        movieId: "1",
        nameRU: "Назад в будущее 1",
        nameEN: "Back to the Future"
    },
    {
        country: "США",
        director: "Роберт Земекис",
        duration: "35",
        year: "2018",
        description: "О чём-то там",
        image: "https://www.film.ru/sites/default/files/styles/thumb_1024x450/public/movies/frames/1615989-1576855.jpeg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user125",
        movieId: "2",
        nameRU: "Назад в будущее 2",
        nameEN: "Back to the Future"
    },
    {
        country: "США",
        director: "Роберт Земекис",
        duration: "35",
        year: "2018",
        description: "О чём-то там Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        image: "https://www.film.ru/sites/default/files/styles/thumb_1024x450/public/movies/frames/1615989-1576855.jpeg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user12",
        movieId: "3",
        nameRU: "Назад в будущее 3",
        nameEN: "Back to the Future"
    },
    {
        country: "США",
        director: "Роберт Земекис",
        duration: "35",
        year: "2018",
        description: "О чём-то там Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        image: "https://www.film.ru/sites/default/files/styles/thumb_1024x450/public/movies/frames/1615989-1576855.jpeg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user12",
        movieId: "4",
        nameRU: "Назад в будущее ещё поедем",
        nameEN: "Back to the Future"
    },
    {
        country: "США",
        director: "Роберт Земекис",
        duration: "35",
        year: "2018",
        description: "О чём-то там Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        image: "https://www.film.ru/sites/default/files/styles/thumb_1024x450/public/movies/frames/1615989-1576855.jpeg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user12",
        movieId: "5",
        nameRU: "Назад в будущее ну послений раз",
        nameEN: "Back to the Future"
    },
    {
        country: "США",
        director: "Роберт Земекис",
        duration: "35",
        year: "2018",
        description: "О чём-то там Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        image: "https://www.film.ru/sites/default/files/styles/thumb_1024x450/public/movies/frames/1615989-1576855.jpeg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user12",
        movieId: "6",
        nameRU: "Назад в будущее ну точно последний",
        nameEN: "Back to the Future"
    },
    {
        country: "США",
        director: "Роберт Земекис",
        duration: "35",
        year: "2018",
        description: "О чём-то там Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        image: "https://www.film.ru/sites/default/files/styles/thumb_1024x450/public/movies/frames/1615989-1576855.jpeg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user12",
        movieId: "7",
        nameRU: "Назад в будущее вот теперь прям сто процентов",
        nameEN: "Back to the Future"
    },
    {
        country: "США",
        director: "Роберт Земекис",
        duration: "35",
        year: "2018",
        description: "О чём-то там Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        image: "https://rg.ru/uploads/images/gallery/fd365c4d/6_259652bb.jpeg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user12",
        movieId: "8",
        nameRU: "смена картинки",
        nameEN: "suddenly"
    },
    {
        country: "США",
        director: "Роберт Земекис",
        duration: "35",
        year: "2018",
        description: "О чём-то там Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        image: "https://rg.ru/uploads/images/150/39/31/2_654e7c00.jpg",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user12",
        movieId: "9",
        nameRU: "Три билборда на границе Эббинга, Миссури",
        nameEN: "Three Billboards Outside Ebbing, Missouri"
    },
    {
        country: "США",
        director: "Роберт Земекис",
        duration: "35",
        year: "2018",
        description: "О чём-то там Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        image: "https://i.playground.ru/p/Qqqz6Q6AFYpFbNWhFDK76g.png",
        trailerLink: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        thumbnail: "https://static.rustore.ru/apk/256380351/content/ICON/d4db7e5a-8a8d-46ad-9509-1cefcf2e40ab.jpg",
        owner: "user12",
        movieId: "10",
        nameRU: "Остановимся на этом",
        nameEN: "Let's stop there"
    },
]